#!/bin/bash

echo "📸 SnapWidget セットアップガイド"
echo "================================="
echo ""
echo "🎯 SnapWidgetでInstagramギャラリーを作成する詳しい手順："
echo ""
echo "1️⃣ アカウント作成"
echo "   • https://snapwidget.com にアクセス"
echo "   • 「Sign Up」をクリック"
echo "   • メールアドレスとパスワードを入力"
echo ""
echo "2️⃣ ウィジェット作成"
echo "   • ダッシュボードで「Create Widget」をクリック"
echo "   • 「Instagram」を選択"
echo "   • プラン選択（無料プランでも使用可能）"
echo ""
echo "3️⃣ Instagram接続"
echo "   • 「Connect Instagram」をクリック"
echo "   • Instagramにログイン"
echo "   • @toriaezu_uc アカウントを認証"
echo ""
echo "4️⃣ カスタマイズ設定"
echo "   • Layout: Grid (グリッド表示)"
echo "   • Photos: 表示したい投稿数（20-50推奨）"
echo "   • Columns: 3または4列"
echo "   • Spacing: Medium"
echo "   • Show captions: Yes（キャプション表示）"
echo ""
echo "5️⃣ 埋め込みコード取得"
echo "   • 設定完了後「Get Code」をクリック"
echo "   • HTMLコードをコピー"
echo ""
echo "6️⃣ WordPressに追加"
echo "   • https://uc.x0.com/wp-admin にログイン"
echo "   • 「Pages」→「Greatest Moments」を編集"
echo "   • 「Custom HTML」ブロックを追加"
echo "   • コピーしたコードを貼り付け"
echo "   • 「Update」をクリック"
echo ""
echo "⚠️  トラブルシューティング："
echo "   • コードが表示されない → ブラウザの広告ブロッカーを無効化"
echo "   • 投稿が表示されない → Instagram Business/Creatorアカウントに変更"
echo "   • エラーが出る → Instagram APIの権限を再確認"
echo ""
echo "🎉 完了後："
echo "   • https://uc.x0.com/greatest-moments/ で確認"
echo "   • 新しいInstagram投稿は自動で更新される"
echo ""
echo "💡 ヒント："
echo "   • 無料プランで十分機能します"
echo "   • モバイルでも美しく表示されます"
echo "   • 投稿をクリックするとInstagramに移動します"