#!/usr/bin/env python3
"""
Generate a test video in English using pre-made avatar images.

This script creates a debate video with English dialogue using the
existing avatar images in data/test_avatars/.
"""
import shutil
from pathlib import Path
from datetime import datetime
import yaml

from src.agents.debate_orchestrator import DebateOrchestrator
from src.nlp.summarize import DebateTopic
from src.tts.gcloud_tts import GoogleCloudTTSProvider
from src.video.video_generator import VideoGenerator
from src.audio.mix import AudioMixer
from src.shared.settings import get_settings


def main():
    """Generate an English debate video."""
    print("=" * 60)
    print("English Debate Video Generation")
    print("=" * 60)
    print()

    # Setup paths
    work_dir = Path("data/work/test_video_en")
    work_dir.mkdir(parents=True, exist_ok=True)

    avatar_source_dir = Path("data/test_avatars")

    audio_stems_dir = work_dir / "audio_stems"
    audio_stems_dir.mkdir(parents=True, exist_ok=True)

    video_dir = work_dir / "video"
    video_dir.mkdir(parents=True, exist_ok=True)

    # Avatar directory for VideoGenerator (must match VideoGenerator's expected path)
    avatar_dest_dir = video_dir / "avatars"
    avatar_dest_dir.mkdir(parents=True, exist_ok=True)

    # Copy existing avatar images to work directory
    print("Copying existing avatar images...")
    for avatar_file in avatar_source_dir.glob("avatar_*.png"):
        dest_file = avatar_dest_dir / avatar_file.name
        if not dest_file.exists():
            shutil.copy2(avatar_file, dest_file)
            print(f"  Copied: {avatar_file.name}")
    print()

    # Load English character configurations
    print("Loading character configurations...")
    config_path = Path("configs/characters_en.yaml")
    with open(config_path, 'r', encoding='utf-8') as f:
        characters = yaml.safe_load(f)
    print(f"  Loaded {len(characters)} characters")
    print()

    # Create debate topic
    topic = DebateTopic(
        title="Can AI Truly Be Creative?",
        summary=(
            "With advances in AI technology, AI is now being used in various creative "
            "activities such as music, painting, and writing. But can the content "
            "generated by AI be considered truly 'creative' in the real sense? "
            "We debate the difference between human and AI creativity."
        ),
        key_points=[
            "AI can learn from existing data and create new combinations",
            "However, AI lacks emotions and experiences, questioning true creativity",
            "What is human creativity and how does it differ from AI creativity?"
        ],
        source_articles=["Test article"]
    )

    print(f"Topic: {topic.title}")
    print(f"Summary: {topic.summary}")
    print()

    # Generate debate script
    print("Generating debate script...")
    orchestrator = DebateOrchestrator(date=datetime.now())
    script = orchestrator.generate_script(topic, target_duration_min=2)

    print(f"  Generated {len(script.lines)} lines")
    print(f"  Estimated duration: {script.total_duration_sec:.1f} seconds")
    print()

    # Display script
    print("=" * 60)
    print("Debate Script")
    print("=" * 60)
    for i, line in enumerate(script.lines, 1):
        char = characters.get(line.speaker, {})
        persona = char.get("persona_name", line.speaker)
        print(f"{i:2}. [{persona}]")
        print(f"    {line.text}")
        print()

    # Generate audio using Google Cloud TTS
    print("=" * 60)
    print("Generating audio (using Google Cloud TTS)...")

    # Load settings to get voice configurations
    settings = get_settings()

    # Voice configurations for each speaker (English voices)
    voice_configs = {
        "chatgpt": {
            "voice_name": "en-US-Neural2-D",  # Male, formal voice
            "speaking_rate": 1.0
        },
        "gemini": {
            "voice_name": "en-US-Neural2-A",  # Male, energetic voice
            "speaking_rate": 1.05
        },
        "claude": {
            "voice_name": "en-US-Neural2-J",  # Male, calm voice
            "speaking_rate": 0.95
        }
    }

    audio_files = []
    for i, line in enumerate(script.lines):
        output_path = audio_stems_dir / f"{i:03d}_{line.speaker}.wav"

        # Get voice config for this speaker
        voice_config = voice_configs.get(line.speaker, voice_configs["chatgpt"])

        # Create TTS provider for this speaker
        tts = GoogleCloudTTSProvider(
            voice_name=voice_config["voice_name"],
            language_code="en-US",
            speaking_rate=voice_config["speaking_rate"]
        )

        # Synthesize audio
        tts.synthesize(
            text=line.text,
            speaker=line.speaker,
            output_path=output_path
        )
        audio_files.append(output_path)
        print(f"  Generated: {output_path.name}")
    print()

    # Mix audio
    print("Mixing audio...")
    mixer = AudioMixer()
    mixed_audio_path = work_dir / "mixed_audio.mp3"

    mixer.mix_podcast(
        voice_files=audio_files,
        output_path=mixed_audio_path,
        bgm_path=None,  # No background music for test
        crossfade_ms=0  # No crossfade for clearer speaker separation
    )
    print(f"  Mixed: {mixed_audio_path}")
    print()

    # Generate video
    print("Generating video...")
    video_gen = VideoGenerator(video_dir, characters)
    output_video = work_dir / "debate_video_en.mp4"

    video_gen.generate_video(
        script=script,
        audio_path=mixed_audio_path,
        output_path=output_video,
        audio_stems_dir=audio_stems_dir
    )

    print()
    print("=" * 60)
    print("✓ Video generation completed!")
    print("=" * 60)
    print(f"Output file: {output_video}")
    print(f"Size: {output_video.stat().st_size / 1024 / 1024:.2f} MB")
    print()


if __name__ == "__main__":
    main()
